# .github/workflows/deploy.yml
name: Build & Deploy QA Hub

# Grant write access to contents (so we can push) and pages (for Pages API)
permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ test ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - name: Deploy to GitHub Pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: deploy
          force_orphan: true
